all:
	gcc thread.c -o thread -lpthread 
	gcc multi_thread.c -o multi_thread -lpthread
	gcc ctrl_thread.c -o ctrl_thread -lpthread
	gcc ctrl_multi_thread.c -o ctrl_multi_thread -lpthread
clean:
	rm -f ./thread ./multi_thread ./ctrl_thread ./ctrl_multi_thread
